//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVManagerAppDT.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class AppDTEntities : DbContext
    {
        public AppDTEntities()
            : base("name=AppDTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<USUARIOS_PV> USUARIOS_PV { get; set; }
        public DbSet<VENTASTICKET_PV> VENTASTICKET_PV { get; set; }
        public DbSet<vis_fillProduct> vis_fillProduct { get; set; }
        public DbSet<TICKETS_PV> TICKETS_PV { get; set; }
        public DbSet<PRODUCTOS_PV> PRODUCTOS_PV { get; set; }
        public DbSet<PAQUETE_DETALLE_PV> PAQUETE_DETALLE_PV { get; set; }
        public DbSet<PAQUETE_PV> PAQUETE_PV { get; set; }
        public DbSet<PEDIDO_SUGERIDO_PV> PEDIDO_SUGERIDO_PV { get; set; }
        public DbSet<vis_fillTickets> vis_fillTickets { get; set; }
    
        public virtual int ps_DELETED_VENTA(Nullable<int> ventaId)
        {
            var ventaIdParameter = ventaId.HasValue ?
                new ObjectParameter("VentaId", ventaId) :
                new ObjectParameter("VentaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ps_DELETED_VENTA", ventaIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> test_appdt(Nullable<int> paquete)
        {
            var paqueteParameter = paquete.HasValue ?
                new ObjectParameter("Paquete", paquete) :
                new ObjectParameter("Paquete", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("test_appdt", paqueteParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Stock_Paquete(Nullable<int> paquete)
        {
            var paqueteParameter = paquete.HasValue ?
                new ObjectParameter("Paquete", paquete) :
                new ObjectParameter("Paquete", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Stock_Paquete", paqueteParameter);
        }
    }
}
