//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVManagerAppDT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAQUETE_DETALLE_PV
    {
        public int Paqd_Id { get; set; }
        public int Paqu_Id { get; set; }
        public string Prod_Id { get; set; }
        public int Prod_Cant { get; set; }
    }
}
