//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVManagerAppDT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_SUGERIDO_PV
    {
        public int Pedi_Id { get; set; }
        public string Sucu_Id { get; set; }
        public int Prod_Id { get; set; }
        public decimal Prod_Stock { get; set; }
        public string Prod_date { get; set; }
        public int Pedi_Status { get; set; }
    }
}
