//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVManagerAppDT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vis_fillTicket
    {
        public int Ticket_Id { get; set; }
        public decimal Venta_Cantidad { get; set; }
        public string Prod_Desc { get; set; }
        public decimal Venta_Importe { get; set; }
    }
}
